global:
  scrape_interval: 10s

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ['192.168.1.100:9100']

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['192.168.1.100:9093']

rule_files:
  - "rules/*.yml"
